import streamlit as st


def apply_styles() -> None:
    st.markdown(
        
        """<style>
        @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@500&family=Inter:wght@400;500;600&family=Manrope:wght@600;700;800&display=swap');
        :root{--ink:#151A21;--slate:#5B6472;--mist:#9AA3AF;--paper:#F6F7F9;--card:#FFF;--line:#E4E7EC;--teal:#0E7C7B;--teal-tint:#E3F4F3;--violet:#6D4AFF;--violet-tint:#EEEAFF;--coral:#F4633A;--coral-tint:#FEEAE4;--amber-tint:#FDF2E2;--green:#12855F;--green-tint:#E3F6EF}
        html,body,[class*="css"]{font-family:Inter,sans-serif}.stApp{color:var(--ink);background:radial-gradient(circle at 12% -15%,var(--teal-tint),transparent 42%),radial-gradient(circle at 100% -5%,var(--violet-tint),transparent 38%),var(--paper)}
        [data-testid="stSidebar"],[data-testid="collapsedControl"]{display:none!important}[data-testid="stHeader"]{background:rgba(255,255,255,.94);border-bottom:1px solid var(--line)}
        [data-testid="stAppViewContainer"] .main .block-container{width:100%!important;max-width:1100px!important;padding:4.2rem 28px 2rem!important}
        h1,h2,h3{font-family:Manrope,sans-serif!important;color:var(--ink)!important}h1{font-size:30px!important;letter-spacing:-.02em}.page-lead{color:var(--slate)!important;margin-top:-.4rem;margin-bottom:1.4rem}
        .brand{display:flex;align-items:center;gap:10px;margin:0 0 .7rem}.brand-mark{width:34px;height:34px;border-radius:9px;display:grid;place-items:center;color:#fff!important;background:linear-gradient(160deg,var(--teal),var(--violet));font:800 15px Manrope}.brand-name{font:700 17px Manrope}
        [data-testid="stRadio"],[data-testid="stRadio"]>div{width:100%!important}[data-testid="stRadio"] div[role="radiogroup"]{display:grid!important;grid-template-columns:repeat(5,minmax(0,1fr))!important;width:100%!important;gap:4px;padding:6px;margin-bottom:1.25rem;background:#fff;border:1px solid var(--line);border-radius:12px}
        [data-testid="stRadio"] div[role="radiogroup"] label{width:100%!important;min-width:0!important;min-height:40px;display:flex!important;align-items:center;justify-content:center;margin:0!important;padding:.35rem .45rem!important;border-radius:8px;cursor:pointer}[data-testid="stRadio"] div[role="radiogroup"] label:has(input:checked){background:var(--teal-tint)}[data-testid="stRadio"] div[role="radiogroup"] label:has(input:checked) p{color:var(--teal)!important;font-weight:600}
        .hero{max-width:650px;margin:2rem auto 1.4rem;text-align:center}.eyebrow{font:500 12px 'IBM Plex Mono';letter-spacing:.08em;text-transform:uppercase;color:var(--teal)!important;margin-bottom:.7rem}.hero h1{font-size:36px!important;margin:.2rem 0 .8rem}.hero .lead{max-width:520px;margin:auto;color:var(--slate);font-size:15.5px;line-height:1.6}
        .card{height:100%;padding:20px;background:#fff;border:1px solid var(--line);border-left:4px solid var(--teal);border-radius:3px 18px 18px 3px}.card.violet-edge{border-left-color:var(--violet)}.card.coral-edge{border-left-color:var(--coral)}.card h3{font-size:16px;margin:12px 0 6px}.card p{color:var(--slate);font-size:13.5px;line-height:1.55}.icon-box{width:36px;height:36px;display:grid;place-items:center;border-radius:10px;color:var(--teal)!important;background:var(--teal-tint);font-weight:700}
        .notice{margin:18px 0;padding:14px 17px;border-radius:16px;font-size:13.5px;line-height:1.55}.notice-teal{background:var(--teal-tint);color:#0B5F5E!important}.notice-amber{background:var(--amber-tint);color:#8A5C15!important}.notice-coral{background:var(--coral-tint);color:#A3391E!important}
        .chips{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0 18px}.chips span{padding:6px 12px;border:1px solid var(--line);border-radius:999px;background:#fff;color:var(--slate);font-size:12px}.section-divider{border-top:1px solid var(--line);margin:26px 0 20px}.result-label{font:500 11.5px 'IBM Plex Mono';letter-spacing:.06em;text-transform:uppercase;color:var(--mist)!important}.result-card,.metric-card,.doc-card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:18px}.pill,.status{display:inline-block;padding:5px 11px;border-radius:999px;font-size:12px;font-weight:600}.pill-teal{background:var(--teal-tint);color:var(--teal)!important}.result-answer{margin:16px 0;color:var(--slate);line-height:1.65}
        .step-row{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:8px 0 22px}.step-row div{display:flex;align-items:center;gap:10px;padding:12px;background:#fff;border:1px solid var(--line);border-radius:12px}.step-row b{width:26px;height:26px;display:grid;place-items:center;border-radius:50%;background:var(--teal-tint);color:var(--teal)}.step-row span{font-size:13px}.progress-label{color:var(--slate)!important}
        [data-testid="stExpander"]{background:#fff;border:1px solid var(--line)!important;border-radius:12px!important}.stButton>button,.stDownloadButton>button{min-height:40px;border-radius:10px;font-weight:600}.stButton>button[kind="primary"]{background:var(--teal);border-color:var(--teal)}.stTextArea textarea,[data-testid="stFileUploaderDropzone"]{background:#fff;border-radius:10px}.footer{margin:2.2rem 0 0;text-align:center;color:var(--mist)!important;font-size:12px}
        @media(max-width:800px){[data-testid="stAppViewContainer"] .main .block-container{padding:4rem 18px 1.5rem!important}[data-testid="stRadio"] div[role="radiogroup"]{grid-template-columns:repeat(2,minmax(0,1fr))!important}.hero{margin-top:1rem}.hero h1{font-size:28px!important}.step-row{grid-template-columns:1fr}}
        </style>""",
        unsafe_allow_html=True,
    )
